// Package storage owns the bytes-only contract for the artifact
// registry. Implementations ("fs", "s3", future backends) write,
// read, stat, and delete opaque objects keyed by ObjectRef. The
// pkg/artifacts.Manager NEVER reaches around this interface — all
// bytes flow through Storage.{Put,Open,LocalPath,Stat,Delete}.
//
// Backend rules (see specs/008-artifact-registry/contracts/storage-interface.md):
//
//   - Name() is stable across process lifetimes (persisted into
//     artifacts.storage_backend at Put time).
//   - Put streams; bounded buffer; no full-source buffering.
//   - Stat returns ErrNotFound for missing objects (used by cleanup).
//   - Delete is idempotent on ErrNotFound (cleanup logs + continues).
//   - LocalPath is a capability hint: backends that cannot expose a
//     path return (_, false, nil); error responses are reserved for
//     true I/O failures.
//   - No goroutine leaks from constructors. No init().
package storage

import (
	"context"
	"errors"
	"io"
	"time"
)

// Sentinel errors. Backends MUST wrap these (e.g. via fmt.Errorf
// "%w"-formatting) so callers can errors.Is them.
var (
	// ErrNotFound — the requested object does not exist in this
	// backend. Cleanup treats this as success (idempotent).
	ErrNotFound = errors.New("artifacts/storage: not found")

	// ErrNotImplemented — the backend recognises the call but cannot
	// fulfil it (e.g. the s3 stub on phase 3). Manager surfaces this
	// to the LLM as a tool envelope rather than aborting the calling
	// mission.
	ErrNotImplemented = errors.New("artifacts/storage: backend not implemented")
)

// ObjectRef identifies a stored object inside a backend. Manager
// holds it; backends decode it. The Backend field MUST equal the
// Storage's Name() — mismatched calls return ErrNotFound.
type ObjectRef struct {
	Backend string
	Key     string
}

// PutHint is metadata the backend may use to derive its key. All
// fields are optional from the manager's perspective; backends MUST
// tolerate any combination of zero values.
type PutHint struct {
	// ID is the artifact id ("art_<short>_<ts>_<rnd>") generated by
	// the manager.
	ID string

	// Name is the producer-supplied display name (sanitised by the
	// manager before being passed in).
	Name string

	// Type is the artifact's type ("parquet", "csv", "html", ...).
	Type string

	// SizeHint is the source size in bytes, -1 when unknown.
	SizeHint int64

	// ContentType is an optional MIME hint (e.g. "application/json").
	ContentType string
}

// Stat reports size + mtime + best-effort MIME type for a stored
// object.
type Stat struct {
	Size        int64
	ModTime     time.Time
	ContentType string // empty when the backend cannot determine it
}

// Storage is the bytes-only contract every backend implements. NO
// knowledge of business rules, visibility, embeddings, DB rows, or
// session lifecycle.
type Storage interface {
	// Name returns the registered backend name (e.g. "fs", "s3").
	// Persisted into artifacts.storage_backend at Put time so a
	// future backend swap does not invalidate historical reads.
	Name() string

	// Put streams the bytes from src into the backend and returns
	// the ObjectRef the manager will store. Caller closes src.
	Put(ctx context.Context, hint PutHint, src io.Reader) (ObjectRef, error)

	// Open returns a streaming reader for the bytes at ref. ref.Backend
	// MUST equal Name(); mismatches surface as ErrNotFound.
	Open(ctx context.Context, ref ObjectRef) (io.ReadCloser, error)

	// Stat reports size + mtime + best-effort content-type. Returns
	// ErrNotFound when the object is missing.
	Stat(ctx context.Context, ref ObjectRef) (Stat, error)

	// Delete removes the bytes at ref. Idempotent on ErrNotFound;
	// other errors surface to the caller (cleanup logs + continues
	// per artifact).
	Delete(ctx context.Context, ref ObjectRef) error

	// LocalPath returns a filesystem path the embedded analytical
	// engine can open via read_parquet / read_csv / read_json_auto.
	// Backends without a local mount return ("", false, nil) —
	// not an error. True I/O failures return (_, false, err).
	LocalPath(ctx context.Context, ref ObjectRef) (path string, ok bool, err error)
}
